# This is a basic workflow to help you get started with Actions
name: Merge and deploy files by schedules

# Controls when the workflow will run
on:
  repository_dispatch:
    types: [trigger-ththethao-from-cronjob]
    
  workflow_dispatch: # Allows you to run the action manually for testing
  
permissions:
  contents: write # Required to push changes back to the repo
  pages: write # Required to deploy github pages
  id-token: write # Required to deploy github pages

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: github
  cancel-in-progress: true
  
jobs:
  merge-commit-and-deploy:
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Start the job
      - name: Start the job
        run: |
          echo Hello, world! 

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
        uses: actions/checkout@v4
          
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests tqdm aiohttp lxml pysocks
      - name: Show current time
        run: |
          echo "Current datetime: $(date)"
          python helloworld.py
          git pull
          
      - name: Download file via curl
        run: |
          curl -s -k -L -o bongda.m3u ${{ secrets.URL_BONGDA }}  &  
          # curl -s -k -L -o pktv.m3u ${{ secrets.URL_PK_TV }}  & 
          curl -s -k -L -o linhtv.json ${{ secrets.URL_LINH_REPO }}/channels.json  & 
          # curl -s -k -L -o vatv.m3u ${{ secrets.URL_VATV }}  & 
          # curl -s -k -L -o linhtv.m3u ${{ secrets.URL_LINH_REPO }}/full.m3u  & 
          
          curl -s -k -H "Authorization: token ${{ secrets.MY_SECRET_PAT }}" -L -o thethao-base.m3u ${{ secrets.URL_PRIVATE_FILES_REPO }}/thethao-base.m3u  & 
          curl -s -k -H "Authorization: token ${{ secrets.MY_SECRET_PAT }}" -L -o xoilacztv.py ${{ secrets.URL_PRIVATE_FILES_REPO }}/python/xoilacztv.py  & 
          curl -s -k -H "Authorization: token ${{ secrets.MY_SECRET_PAT }}" -L -o json2m3u.py ${{ secrets.URL_PRIVATE_FILES_REPO }}/python/json2m3u.py & 
          curl -s -k -H "Authorization: token ${{ secrets.MY_SECRET_PAT }}" -L -o extractm3u.py ${{ secrets.URL_PRIVATE_FILES_REPO }}/python/extractm3u.py & 
          curl -s -k -H "Authorization: token ${{ secrets.MY_SECRET_PAT }}" -L -o removem3u.py ${{ secrets.URL_PRIVATE_FILES_REPO }}/python/removem3u.py & 
          curl -s -k -H "Authorization: token ${{ secrets.MY_SECRET_PAT }}" -L -o apisports.py ${{ secrets.URL_PRIVATE_FILES_REPO }}/python/apisports.py & 
          curl -s -k -H "Authorization: token ${{ secrets.MY_SECRET_PAT }}" -L -o fixjson.py ${{ secrets.URL_PRIVATE_FILES_REPO }}/python/fixjson.py & 
          curl -s -k -H "Authorization: token ${{ secrets.MY_SECRET_PAT }}" -L -o testproxies.py ${{ secrets.URL_PRIVATE_FILES_REPO }}/python/testproxies.py & 
          curl -s -k -H "Authorization: token ${{ secrets.MY_SECRET_PAT }}" -L -o keys.json ${{ secrets.URL_PRIVATE_FILES_REPO }}/jsonfiles/keys.json & 
          
          # download previous m3u files, for next use
          curl -s -k -L -o quechoatv.m3u https://thcoban.github.io/ththethao/quechoatv.m3u  &
          curl -s -k -L -o tieulamtv.m3u https://thcoban.github.io/ththethao/tieulamtv.m3u  &
          curl -s -k -L -o xoilacztv.m3u https://thcoban.github.io/ththethao/xoilacztv.m3u  &
          curl -s -k -L -o hoiquantv.m3u https://thcoban.github.io/ththethao/hoiquantv.m3u  &
          curl -s -k -L -o khandaiatv.m3u https://thcoban.github.io/ththethao/khandaiatv.m3u  &
          curl -s -k -L -o xaycontv.m3u https://thcoban.github.io/ththethao/xaycontv.m3u  &
          curl -s -k -L -o colatv.m3u https://thcoban.github.io/ththethao/colatv.m3u  &
          curl -s -k -L -o bugiotv.m3u https://thcoban.github.io/ththethao/bugiotv.m3u  &
          curl -s -k -L -o tamquoctv.m3u https://thcoban.github.io/ththethao/tamquoctv.m3u  &
          curl -s -k -L -o cakhiatv.m3u https://thcoban.github.io/ththethao/cakhiatv.m3u  &
          curl -s -k -L -o nauxoitv.m3u https://thcoban.github.io/ththethao/nauxoitv.m3u  &
          curl -s -k -L -o chuoichientv.m3u https://thcoban.github.io/ththethao/chuoichientv.m3u  &
          curl -s -k -L -o luongsontv.m3u https://thcoban.github.io/ththethao/luongsontv.m3u  &
          
          wait
          ls -lh

      - name: Download, get & convert links to M3U files
        run: |
          if [ -f testproxies.py ]; then
            python testproxies.py etc/proxies.txt &
          fi
        
          if [ -f xoilacztv.py ]; then
            # will overwrite previous xoilacztv, if the condition matches
            # python xoilacztv.py https://xoilacz.vip xoilacztv.m3u  & 
            python xoilacztv.py https://xoilacz.io xoilacztv.m3u  & 
          fi
          
          if [ -f apisports.py ]; then
            python apisports.py cakhia cakhiatv.m3u &
            python apisports.py nauxoi nauxoitv.m3u &
            
            python apisports.py khandaia khandaiatv.m3u &
            python apisports.py hoiquan hoiquantv.m3u &
            python apisports.py xaycon xaycontv.m3u &
            python apisports.py cola colatv.m3u &
            python apisports.py bugio bugiotv.m3u &
            python apisports.py tamquoc tamquoctv.m3u &
            python apisports.py chuoichien chuoichientv.m3u &
            python apisports.py quechoa quechoatv.m3u &
            python apisports.py tieulam tieulamtv.m3u &
          fi
          
          # if [ -f json2m3u.py ]; then
          #   python json2m3u.py ${{ secrets.URL_APITHETHAO }}/quechoatv  quechoatv.m3u  1   & 
          #   python json2m3u.py ${{ secrets.URL_APITHETHAO }}/luongsontv  luongsontv.m3u  1   & 
          #   # python json2m3u.py ${{ secrets.URL_APITHETHAO }}/colatv  colatv.m3u  1   & 
          #   # python json2m3u.py ${{ secrets.URL_APITHETHAO }}/gavangtv  gavangtv.m3u  1   & 
          #   # python json2m3u.py ${{ secrets.URL_APITHETHAO }}/cumeotv  cumeotv.m3u  1 
          # fi
          
          if [ -f extractm3u.py ]; then
            # python extractm3u.py pktv.m3u new_pktv.m3u "Cháo Gà"  & 
            # python extractm3u.py vatv.m3u new_vatv.m3u "ColaTV"   &
            
            [ -f bongda.m3u ] && cp bongda.m3u bongda2.m3u
            python extractm3u.py bongda.m3u luongsontv.m3u "Lương sơn" & 
            python extractm3u.py bongda2.m3u socolivetv.m3u "socolive" & 
          fi
          
          # if [ -f removem3u.py ]; then
          #   python removem3u.py bongda.m3u new_bongda.m3u "Khán đài a, Gà vàng, Chuối Chiên" & 
          # fi
          
          if [ -f fixjson.py ]; then
            python fixjson.py linhtv.json ttthethao.json
          fi
          
          wait
      
      # Runs a set of commands using the runners shell
      - name: Merge Files
        # Combine thethao-base.m3u, bongda.m3u and other m3u files into thethao.m3u
        run: |
          # delete old thethao.m3u, ttthethao.m3u before merge
          rm -f thethao.m3u
          rm -f ttthethao.m3u
          mkdir -p m3ufiles
          ls -lh

          if [ -f quechoatv.m3u ]; then
            echo " " >> ttthethao.m3u
            cat quechoatv.m3u >> ttthethao.m3u
            echo " " >> ttthethao.m3u
          fi
          if [ -f xoilacztv.m3u ]; then
            echo " " >> ttthethao.m3u
            cat xoilacztv.m3u >> ttthethao.m3u
            echo " " >> ttthethao.m3u
          fi         
          if [ -f hoiquantv.m3u ]; then
            echo " " >> ttthethao.m3u
            cat hoiquantv.m3u >> ttthethao.m3u
            echo " " >> ttthethao.m3u
          fi
          if [ -f khandaiatv.m3u ]; then
            echo " " >> ttthethao.m3u
            cat khandaiatv.m3u >> ttthethao.m3u
            echo " " >> ttthethao.m3u
          fi
          if [ -f tieulamtv.m3u ]; then
            echo " " >> ttthethao.m3u
            cat tieulamtv.m3u >> ttthethao.m3u
            echo " " >> ttthethao.m3u
          fi
          if [ -f colatv.m3u ]; then
            echo " " >> ttthethao.m3u
            cat colatv.m3u >> ttthethao.m3u
            echo " " >> ttthethao.m3u
          fi
          if [ -f bugiotv.m3u ]; then
            echo " " >> ttthethao.m3u
            cat bugiotv.m3u >> ttthethao.m3u
            echo " " >> ttthethao.m3u
          fi
          if [ -f tamquoctv.m3u ]; then
            echo " " >> ttthethao.m3u
            cat tamquoctv.m3u >> ttthethao.m3u
            echo " " >> ttthethao.m3u
          fi
          if [ -f cakhiatv.m3u ]; then
            echo " " >> ttthethao.m3u
            cat cakhiatv.m3u >> ttthethao.m3u
            echo " " >> ttthethao.m3u
          fi
          if [ -f chuoichientv.m3u ]; then
            echo " " >> ttthethao.m3u
            cat chuoichientv.m3u >> ttthethao.m3u
            echo " " >> ttthethao.m3u
          fi
          if [ -f xaycontv.m3u ]; then
            echo " " >> ttthethao.m3u
            cat xaycontv.m3u >> ttthethao.m3u
            echo " " >> ttthethao.m3u
          fi
          if [ -f nauxoitv.m3u ]; then
            echo " " >> ttthethao.m3u
            cat nauxoitv.m3u >> ttthethao.m3u
            echo " " >> ttthethao.m3u
          fi

          if [ -f new_vatv.m3u ]; then
            echo " " >> ttthethao.m3u
            cat new_vatv.m3u >> ttthethao.m3u
            echo " " >> ttthethao.m3u
          fi

          if [ -f new_pktv.m3u ]; then
            echo " " >> ttthethao.m3u
            cat new_pktv.m3u >> ttthethao.m3u
            echo " " >> ttthethao.m3u
          fi

          if [ -f luongsontv.m3u ]; then
            echo " " >> ttthethao.m3u
            cat luongsontv.m3u >> ttthethao.m3u
            echo " " >> ttthethao.m3u
          fi
          if [ -f socolivetv.m3u ]; then
            echo " " >> ttthethao.m3u
            cat socolivetv.m3u >> ttthethao.m3u
            echo " " >> ttthethao.m3u
          fi

          if [ -f new_bongda.m3u ]; then
            echo " " >> ttthethao.m3u
            cat new_bongda.m3u >> ttthethao.m3u
            echo " " >> ttthethao.m3u
          fi

          cat thethao-base.m3u > thethao.m3u
          echo " " >> thethao.m3u
          cat ttthethao.m3u >> thethao.m3u
          echo " " >> thethao.m3u
          # ls -lh

          [ -f bongda.m3u ] && cp bongda.m3u m3ufiles/
          [ -f thethao.m3u ] && cp thethao.m3u m3ufiles/
          [ -f thethao-base.m3u ] && cp thethao-base.m3u m3ufiles/
          [ -f ttthethao.m3u ] && cp ttthethao.m3u m3ufiles/
          [ -f quechoatv.m3u ] && cp quechoatv.m3u m3ufiles/
          [ -f hoiquantv.m3u ] && cp hoiquantv.m3u m3ufiles/
          [ -f khandaiatv.m3u ] && cp khandaiatv.m3u m3ufiles/
          [ -f xaycontv.m3u ] && cp xaycontv.m3u m3ufiles/
          [ -f colatv.m3u ] && cp colatv.m3u m3ufiles/
          [ -f bugiotv.m3u ] && cp bugiotv.m3u m3ufiles/
          [ -f tamquoctv.m3u ] && cp tamquoctv.m3u m3ufiles/
          [ -f chuoichientv.m3u ] && cp chuoichientv.m3u m3ufiles/
          [ -f cakhiatv.m3u ] && cp cakhiatv.m3u m3ufiles/
          [ -f nauxoitv.m3u ] && cp nauxoitv.m3u m3ufiles/
          [ -f quechoatv.m3u ] && cp quechoatv.m3u m3ufiles/
          [ -f tieulamtv.m3u ] && cp tieulamtv.m3u m3ufiles/

          [ -f luongsontv.m3u ] && cp luongsontv.m3u m3ufiles/
          [ -f socolivetv.m3u ] && cp socolivetv.m3u m3ufiles/
          
          [ -f keys.json ] && cp keys.json m3ufiles/
          [ -f ttthethao.json ] && cp ttthethao.json m3ufiles/

          # keep current xoilacztv.m3u for next use
          [ -f xoilacztv.m3u ] && cp xoilacztv.m3u m3ufiles/
          
          # ls -lh m3ufiles/
          
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload entire repository
          path: 'm3ufiles/'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5        

      - name: Commit and push changes
        run: |
          git config --local user.name "thcoban [bot]"
          git add ttthethao.m3u

          echo "checking any changes"
          if [ git diff --quiet ]; then
            echo "[test only] No changes detected."
          fi
          
          git commit -m "[no ci] Update ttthethao.m3u"
          git push      
