# This is a basic workflow to help you get started with Actions
name: Merge and deploy files by schedules

# Controls when the workflow will run
on:
  # push:  
  workflow_call:
  schedule:
    # Use https://crontab.guru to customize your schedule.
    - cron: "3 * * * *"
    
  workflow_dispatch: # Allows you to run the action manually for testing
  
permissions:
  contents: write # Required to push changes back to the repo
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: github
  cancel-in-progress: true
  
jobs:
  merge-commit-and-deploy:
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Start the job
      - name: Start the job
        run: |
          echo Hello, world! 

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
        uses: actions/checkout@v4
          
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests tqdm aiohttp lxml
      - name: Show current time
        run: |
          echo "Current datetime: $(date)"
          python helloworld.py
      - name: Download file via curl
        run: |
          curl -s -k -f -o bongda.m3u ${{ secrets.URL_BONGDA }}  &  
          curl -s -k -f -L -o vatv.m3u ${{ secrets.URL_VATV }}  & 
          curl -s -k -f -L -o autonomous.m3u https://autonomous-lime-os2knxzlw8.edgeone.app/  & 
          curl -s -k -f -H "Authorization: token ${{ secrets.MY_SECRET_PAT }}" -L -o thethao-base.m3u ${{ secrets.URL_PRIVATE_FILES_REPO }}/thethao-base.m3u  & 
          curl -s -k -f -H "Authorization: token ${{ secrets.MY_SECRET_PAT }}" -L -o xoilacztv.py ${{ secrets.URL_PRIVATE_FILES_REPO }}/python/xoilacztv.py  & 
          curl -s -k -f -H "Authorization: token ${{ secrets.MY_SECRET_PAT }}" -L -o json2m3u.py ${{ secrets.URL_PRIVATE_FILES_REPO }}/python/json2m3u.py & 
          curl -s -k -f -H "Authorization: token ${{ secrets.MY_SECRET_PAT }}" -L -o updatem3u.py ${{ secrets.URL_PRIVATE_FILES_REPO }}/python/updatem3u.py & 
         
          # curl -s -k -f -o socolive_dtt.m3u ${{ secrets.URL_DTT }}/socolive.php  &
          # curl -s -k -f -o luongsontv_dtt.m3u ${{ secrets.URL_DTT }}/luongsontv.php  &
          
          wait
          ls -lh

      - name: Download, get & convert links to M3U files
        run: |
          if [ -f xoilacztv.py ]; then
            # python xoilacztv.py https://xoilacz.vip xoilacztv.m3u  & 
            python xoilacztv.py https://xoilacz.io xoilacztv.m3u  & 
          fi
          if [ -f bunchatv.py ]; then
            python bunchatv.py https://bit.ly/bunchatv bunchatv.m3u  & 
          fi
          if [ -f thapcam24htv.py ]; then
            python thapcam24htv.py https://thapcam24h.net thapcam24htv.m3u  & 
          fi
          if [ -f json2m3u.py ]; then
            python json2m3u.py ${{ secrets.URL_HOIQUANTV }}  hoiquantv.m3u  1  & 
            python json2m3u.py ${{ secrets.URL_APITHETHAO }}/thiendinhtv  thiendinhtv.m3u  1   & 
            python json2m3u.py ${{ secrets.URL_APITHETHAO }}/quechoatv  quechoatv.m3u  1   & 
            python json2m3u.py ${{ secrets.URL_APITHETHAO }}/luongsontv  luongsontv.m3u  1   & 
            python json2m3u.py ${{ secrets.URL_APITHETHAO }}/colatv  colatv.m3u  1   & 
            python json2m3u.py ${{ secrets.URL_APITHETHAO }}/gavangtv  gavangtv.m3u  1   & 
            python json2m3u.py ${{ secrets.URL_APITHETHAO }}/cumeotv  cumeotv.m3u  1 

            #python json2m3u.py https://tinyurl.com/buncha2 bunchatv.m3u  1  & 
            #python json2m3u.py https://tinyurl.com/thapcam2 thapcamfaketv.m3u  1  & 
            #python json2m3u.py https://tinyurl.com/quechoa quechoatv.m3u  1 
          fi
          
          if [ -f updatem3u.py ]; then
            python updatem3u.py socolive_dtt.m3u  & 
            python updatem3u.py luongsontv_dtt.m3u  https://ls10.site/  & 
          fi

          wait
      
      # Runs a set of commands using the runners shell
      - name: Merge Files
        # Combine thethao-base.m3u, bongda.m3u and vietanhtv_playlist into thethao.m3u
        run: |
          # delete old thethao.m3u, ttthethao.m3u before merge
          rm -f thethao.m3u
          rm -f ttthethao.m3u
          mkdir -p m3ufiles
         
          ls -lh

          if [ -f hoiquantv.m3u ]; then
            echo " " >> ttthethao.m3u
            cat hoiquantv.m3u >> ttthethao.m3u
            echo " " >> ttthethao.m3u
          fi

          if [ -f xoilacztv.m3u ]; then
            echo " " >> ttthethao.m3u
            cat xoilacztv.m3u >> ttthethao.m3u
            echo " " >> ttthethao.m3u
          fi

          # merge bottom of vatv.m3u into ttthethao.m3u:
          if [ -f vatv.m3u ]; then
            file_name=vatv.m3u
            line_num=$(awk '/group-title="ColaTV"/ {print NR; exit}' $file_name)
            echo "'$file_name'. Found on line: $line_num"
  
            if [ -z "$line_num" ]; then
                echo "Pattern not found"
            else
              echo "Found on line: $line_num"
              
              # set first K lines:
              K=$(( $line_num - 1 ))
              echo "line_num - 1: $K"
              
              # line count (N):
              N=$(wc -l < $file_name)
              echo "'$file_name'. Total lines: $N"
              
              # length of the bottom file:
              L=$(( $N - $K ))
              echo "length of the bottom file: $L"
              
              # create bottom of file: 
              tail -n $L $file_name > bottom_$file_name
  
              if [ -f bottom_$file_name ]; then
                echo " " >> ttthethao.m3u
                echo "Merge $bottom_$file_name into main file"
                cat bottom_$file_name >> ttthethao.m3u
                echo " " >> ttthethao.m3u
              fi
            fi
          fi

          if [ -f bunchatv.m3u ]; then
            echo " " >> ttthethao.m3u
            cat bunchatv.m3u >> ttthethao.m3u
            echo " " >> ttthethao.m3u
          fi
          if [ -f thapcam24htv.m3u ]; then
            echo " " >> ttthethao.m3u
            cat thapcam24htv.m3u >> ttthethao.m3u
            echo " " >> ttthethao.m3u          
          fi
          
          if [ -f thiendinhtv.m3u ]; then
            echo " " >> ttthethao.m3u
            cat thiendinhtv.m3u >> ttthethao.m3u
            echo " " >> ttthethao.m3u
          fi
          if [ -f quechoatv.m3u ]; then
            echo " " >> ttthethao.m3u
            cat quechoatv.m3u >> ttthethao.m3u
            echo " " >> ttthethao.m3u
          fi
          if [ -f luongsontv.m3u ]; then
            echo " " >> ttthethao.m3u
            cat luongsontv.m3u >> ttthethao.m3u
            echo " " >> ttthethao.m3u
          fi
          if [ -f colatv.m3u ]; then
            echo " " >> ttthethao.m3u
            cat colatv.m3u >> ttthethao.m3u
            echo " " >> ttthethao.m3u
          fi
          if [ -f gavangtv.m3u ]; then
            echo " " >> ttthethao.m3u
            cat gavangtv.m3u >> ttthethao.m3u
            echo " " >> ttthethao.m3u
          fi
          if [ -f cumeotv.m3u ]; then
            echo " " >> ttthethao.m3u
            cat cumeotv.m3u >> ttthethao.m3u
            echo " " >> ttthethao.m3u
          fi

          if [ -f socolive_dtt.m3u ]; then
            echo " " >> ttthethao.m3u
            cat socolive_dtt.m3u >> ttthethao.m3u
            echo " " >> ttthethao.m3u
          fi       
          if [ -f luongsontv_dtt.m3u ]; then
            echo " " >> ttthethao.m3u
            cat luongsontv_dtt.m3u >> ttthethao.m3u
            echo " " >> ttthethao.m3u
          fi
         
          if [ -f bongda.m3u ]; then
            echo " " >> ttthethao.m3u
            cat bongda.m3u >> ttthethao.m3u
            echo " " >> ttthethao.m3u
          fi

          if [ -f autonomous.m3u ]; then
            echo " " >> ttthethao.m3u
            cat autonomous.m3u >> ttthethao.m3u
            echo " " >> ttthethao.m3u
          fi

          cat thethao-base.m3u > thethao.m3u
          echo " " >> thethao.m3u
          cat ttthethao.m3u >> thethao.m3u
          echo " " >> thethao.m3u
          # ls -lh

          cp bongda.m3u m3ufiles/
          cp thethao.m3u m3ufiles/
          cp thethao-base.m3u m3ufiles/
          cp ttthethao.m3u m3ufiles/
          # ls -lh m3ufiles/
          
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload entire repository
          path: 'm3ufiles/'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5        

      - name: Commit and push changes
        run: |
          git config --local user.name "thcoban [bot]"
          git add m3ufiles/ttthethao.m3u
          git commit -m "[no ci] Update ttthethao.m3u"
          git push
