name: Auto merge trigger no.2

# Controls when the workflow will run
on:
  schedule:
    # Runs every hour 0, 1, 2 ...
    # Use https://crontab.guru to customize your schedule.
    - cron: "27/30 * * * *"
  workflow_dispatch: # Allows you to run the action manually for testing
  
jobs:
  call-child:
    permissions:
      contents: write # Required to push changes back to the repo
    # trigger automerge.yml
    uses: ./.github/workflows/automerge.yml
    secrets: inherit # pass all secrets
